101: # Passerby of Wandering Cloud
  2:
    - - OUTGOING_HEALING_BOOST_
      - 10
      - null

102: # Musketeer of Wild Wheat
  2:
    - - ATK_
      - 12
      - null
  4:
    - - SPD_
      - 6
      - null
    - - BASIC_ATK_DMG_BOOST_
      - 10
      - null

103: # Knight of Purity Palace
  2:
    - - DEF_
      - 15
      - null
  4:
    - - SHIELD_DMG_ABSORPTION_
      - 20
      - null

104: # Hunter of Glacial Forest
  2:
    - - ICE_DMG_BOOST_
      - 10
      - null
  # for 4 pieces: After the wearer uses their Ultimate, their CRIT DMG increases by 25% for 2 turn(s).

105: # Champion of Streetwise Boxing
  2:
    - - PHYSICAL_DMG_BOOST_
      - 10
      - null
  # for 4 pieces: After the wearer attacks or is hit, their ATK increases by 5% for the rest of the battle. This effect can stack up to 5 time(s).

106: # Guard of Wuthering Snow
  2:
    - - DMG_REDUCTION_
      - 8
      - null
107: # Firesmith of Lava-Forging
  2:
    - - FIRE_DMG_BOOST_
      - 10
      - null
  4:
    - - SKILL_DMG_BOOST_
      - 12
      - null
    # After unleashing Ultimate, increases the wearer's Fire DMG by 12% for the next attack.

108: # Genius of Brilliant Stars
  2:
    - - QUANTUM_DMG_BOOST_
      - 10
      - null
  # for 4 pieces: When the wearer deals DMG to the target enemy, ignores 10% DEF. If the target enemy has Quantum Weakness, the wearer additionally ignores 10% DEF.

109: # Band of Sizzling Thunder
  2:
    - - LIGHTNING_DMG_BOOST_
      - 10
      - null
  # for 4 pieces: When the wearer uses their Skill, increases the wearer's ATK by 20% for 1 turn(s).

110: # Eagle of Twilight Line
  2:
    - - WIND_DMG_BOOST_
      - 10
      - null

111: # Thief of Shooting Meteor
  2:
    - - BREAK_EFFECT_
      - 16
      - null
  4:
    - - BREAK_EFFECT_
      - 16
      - null

112: # Wastelander of Banditry Desert
  2:
    - - IMAGINARY_DMG_BOOST_
      - 10
      - null
  # for 4 pieces: When attacking debuffed enemies, the wearer's CRIT Rate increases by 10%, and their CRIT DMG increases by 20% against Imprisoned enemies.

113: # Longevous Disciple
  2:
    - - HP_
      - 12
      - null
  # for 4 pieces: When the wearer is hit or has their HP consumed by an ally or themselves, their CRIT Rate increases by 8% for 2 turn(s) and up to 2 stacks.

114: # Messenger Traversing Hackerspace
  2:
    - - SPD_
      - 6
      - null
  
115: # The Ashblazing Grand Duke
  2:
    - - FOLLOW_UP_ATK_DMG_BOOST_
      - 20
      - null
  # for 4 pieces: When the wearer uses a follow-up attack, increases the wearer's ATK by 6% for every time the follow-up attack deals DMG. This effect can stack up to 8 time(s) and lasts for 3 turn(s). This effect is removed the next time the wearer uses a follow-up attack.

116: # Prisoner in Deep Confinement
  2:
    - - ATK_
      - 20
      - null
  # for 4 pieces: For every DoT the target enemy is afflicted with, the wearer will ignore 6% of its DEF when dealing DMG to it. This effect is valid for a max of 3 DoTs.

117: # Pioneer Diver of Dead Waters
  # for 2 pieces: Increases DMG dealt to enemies with debuffs by 12%.
  4:
    - - CRIT_RATE_
      - 4
      - null
  # for 4 pieces: The wearer deals 8%/12% increased CRIT DMG to enemies with at least 2/3 debuffs. After the wearer inflicts a debuff on enemy targets, the aforementioned effects increase by 100%, lasting for 1 turn(s).

118: # Watchmaker, Master of Dream Machinations
  2:
    - - BREAK_EFFECT_
      - 16
      - null

119: # Iron Cavalry Against the Scourge
  2:
    - - BREAK_EFFECT_
      - 16
      - null
  4:
    - - BREAK_DMG_DEF_IGNORE_
      - 10
      - - BREAK_EFFECT_
        - 150
    - - SUPER_BREAK_DMG_DEF_IGNORE_
      - 15
      - - BREAK_EFFECT_
        - 250

120: # The Wind-Soaring Valorous
  2:
    - - ATK_
      - 12
      - null
  4:
    - - CRIT_RATE_
      - 6
      - null
    # After the wearer uses a follow-up attack, increases DMG dealt by Ultimate by 36%, lasting for 1 turn(s).

301: # Space Sealing Station
  2:
    - - ATK_
      - 12
      - null
    - - ATK_
      - 12
      - - SPD
        - 120

302: # Fleet of the Ageless
  2:
    - - HP_
      - 12
      - null

303: # Pan-Cosmic Commercial Enterprise
  2:
    - - EFFECT_HIT_RATE_
      - 10
      - null
    # Meanwhile, the wearer's ATK increases by an amount that is equal to 25% of the current Effect Hit Rate, up to a maximum of 25%.

304: # Belobog of the Architects
  2:
    - - DEF_
      - 15
      - null
    - - DEF_
      - 15
      - - EFFECT_HIT_RATE_
        - 50

305: # Celestial Differentiator
  2:
    - - CRIT_DMG_
      - 16
      - null
    # When the wearer's current CRIT DMG reaches 120% or higher, after entering battle, the wearer's CRIT Rate increases by 60% until the end of their first attack.

306: # Inert Salsotto
  2:
    - - CRIT_RATE_
      - 8
      - null
    - - FOLLOW_UP_ATK_DMG_BOOST_
      - 15
      - - CRIT_RATE_
        - 50
    - - ULTIMATE_DMG_BOOST_
      - 15
      - - CRIT_RATE_
        - 50
  
307: # Talia: Kingdom of Banditry
  2:
    - - BREAK_EFFECT_
      - 16
      - null
    - - BREAK_EFFECT_
      - 20
      - - SPD
        - 145

308: # Sprightly Vonwacq
  2:
    - - ENERGY_REGENERATION_RATE_
      - 5
      - null
    
309: # Rutilant Arena
  2:
    - - CRIT_RATE_
      - 8
      - null
    - - BASIC_ATK_DMG_BOOST_
      - 20
      - - CRIT_RATE_
        - 70
    - - SKILL_DMG_BOOST_
      - 20
      - - CRIT_RATE_
        - 70

310: # Broken Keel
  2:
    - - EFFECT_RES_
      - 10
      - null

311: # Firmament Frontline: Glamoth
  2:
    - - ATK_
      - 12
      - null
    - - DMG_BOOST_
      - 12
      - - SPD
        - 135
    - - DMG_BOOST_
      - 18
      - - SPD
        - 160

312: # Penacony, Land of the Dreams
  2:
    - - ENERGY_REGENERATION_RATE_
      - 5
      - null
    # Increases DMG by 10.00% for all other allies that are of the same Type as the wearer.

313: # Sigonia, the Unclaimed Desolation
  2:
    - - CRIT_RATE_
      - 4
      - null
    # When an enemy target gets defeated, the wearer's CRIT DMG increases by 4.00%, stacking up to 10 time(s).

314: # Izumo Gensei and Takama Divine Realm
  2:
    - - ATK_
      - 12
      - null
    # When entering battle, if at least one teammate follows the same Path as the wearer, then the wearer's CRIT Rate increases by 12.00%.

# 315: # Duran, Dynasty of Running Wolves
#   2:
  # When an ally uses a follow-up attack, the wearer gains 1 stack of Merit, stacking up to 5 time(s). Each stack of Merit increases the DMG dealt by the wearer's follow-up attacks by 5.00%. When there are 5 stacks, additionally increases the wearer's CRIT DMG by 25.00%.

316: # Forge of the Kalpagni Lantern
  2:
    - - SPD_
      - 6
      - null
    #  When the wearer hits an enemy target that has Fire Weakness, the wearer's Break Effect increases by 40.00%, lasting for 1 turn(s).

317: # Lushaka, the Sunken Seas
  2:
    - - ENERGY_REGENERATION_RATE_
      - 5
      - null
    # If the wearer is not the first character in the team lineup, then increases the ATK of the first character in the team lineup by 12.00%.

318: # The Wondrous BananAmusement Park
  2:
    - - CRIT_DMG_
      - 16
      - null
    # When a target summoned by the wearer is on the field, CRIT DMG additionally increases by 32.00%.